AWSTemplateFormatVersion: '2010-09-09'
Description: 'EC2 Instance Deployment'

Parameters:
  AmiId:
    Type: String
    Description: AMI ID for EC2 instance

  InstanceType:
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - t2.small
      - t2.medium

Resources:
  EC2SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow SSH
      VpcId: 'vpc-030129817322a4f14'
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0

  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      ImageId: !Ref AmiId
      SubnetId: 'subnet-0ef65729144bffce9'
      SecurityGroupIds:
        - !Ref EC2SecurityGroup
