AWSTemplateFormatVersion: '2010-09-09'
Description: 'RDS MySQL Instance'

Parameters:
  DBUsername:
    Type: String
    Default: rayRds
  DBPassword:
    Type: String
    NoEcho: true
    Default: rayRdsPassword

Resources:
  RdsSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow MySQL access
      VpcId: vpc-030129817322a4f14
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 3306
          ToPort: 3306
          CidrIp: 0.0.0.0/0

  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: RDS Subnet Group
      SubnetIds:
        - subnet-0ef65729144bffce9
        - subnet-0ec43e97e6e8afcbd
      Tags:
        - Key: Name
          Value: RayDBSubnetGroup

  RDSInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBName: assignment3
      AllocatedStorage: 20
      DBInstanceClass: db.t3.micro
      Engine: mysql
      EngineVersion: '8.0'
      MasterUsername: !Ref DBUsername
      MasterUserPassword: !Ref DBPassword
      PubliclyAccessible: true
      VPCSecurityGroups:
        - !Ref RdsSecurityGroup
      DBSubnetGroupName: !Ref DBSubnetGroup
